# docker-compose.yml
version: "3"
services:
  app:
    container_name: byteframe-backend
    build: .
    depends_on:
      - postgres
    environment:
      GOOGLE_KEY: "xxx"
      URL_BACKEND: "https://byteframe.etiennepasteur.com/"
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: byteframe-postgres
    image: postgres:10.4
    ports:
      - "35432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

volumes:
  postgres-data:
